import os
import json
from jinja2 import Environment, FileSystemLoader

def load_projects_metadata():
    """Load all projects metadata generated by update-all-projects.py"""
    metadata_path = './assets/js/projects-metadata.json'
    if not os.path.exists(metadata_path):
        print("Warning: projects-metadata.json not found. Run update-all-projects.py first.")
        return []
    
    with open(metadata_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def get_recent_posts_per_category(projects_data, limit=3):
    """Get top N recent posts for each project category"""
    recent_by_category = []
    
    for project_data in projects_data:
        config = project_data['config']
        posts = project_data['posts']
        
        # Get top N posts (already sorted by date in update-all-projects.py)
        recent_posts = posts[:limit] if len(posts) >= limit else posts
        
        recent_by_category.append({
            'config': config,
            'recent_posts': recent_posts
        })
    
    return recent_by_category

def update_homepage():
    """Generate homepage with recent posts from all project categories"""
    # Load projects data
    projects_data = load_projects_metadata()
    
    # Get 3 recent posts per category
    recent_by_category = get_recent_posts_per_category(projects_data, limit=3)
    
    # Jinja2 environment
    env = Environment(loader=FileSystemLoader(searchpath="./"))
    template = env.get_template('./temp-index.html')
    
    # Render template
    output = template.render(projects_categories=recent_by_category)
    
    # Write to index.html
    with open('./index.html', 'w', encoding='utf-8') as f:
        f.write(output)
    
    print("✅ Homepage updated successfully!")

def update_about_page():
    """Generate about page"""
    env = Environment(loader=FileSystemLoader(searchpath="./"))
    template = env.get_template('./temp-about.html')
    
    output = template.render()
    
    os.makedirs('./about', exist_ok=True)
    with open('./about/index.html', 'w', encoding='utf-8') as f:
        f.write(output)
    
    print("✅ About page updated successfully!")

if __name__ == "__main__":
    update_homepage()
    update_about_page()