name: Update Project Pages

on:
  push:
    paths:
      - 'mdposts/projects/**'
  workflow_dispatch:  # 수동 트리거 가능하도록 추가

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false # 기존 자격 증명 대신 GITHUB_TOKEN 사용

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update Project Pages
      run: |
        python assets/py/update-project-page.py  # Projects 페이지 업데이트 스크립트 실행

    - name: Update Index Page
      run: |
        python assets/py/update-index-page.py  # 공통 인덱스 업데이트 스크립트 실행

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions Bot"
        git add .
        git commit -m "Auto-update blog pages and index"
        git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}